---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    route.openshift.io/termination: edge
spec:
  ingressClassName: openshift-default
  defaultBackend:
    service:
      name: hello-world
      port:
        number: 8080
  tls:
    - hosts:
        - {{ hostname }}
      secretName: hello-world-tls
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - backend:
              service:
                name: hello-world
                port:
                  number: 8080
